// <auto-generated>
// This file is auto-generated. Do not edit manually.
// </auto-generated>

using System;
using Model.Enum.Named;

namespace Managers.GameStates
{
    public static class GameStateFactory
    {
        public static IGameState Create(NamedState state)
        {
            return state switch
            {
                NamedState.GameLoad => new GameLoadState(),
                NamedState.Gameplay => new GameplayState(),
                NamedState.MainMenu => new MainMenuState(),
                NamedState.PauseMenu => new PauseMenuState(),
                _ => throw new ArgumentOutOfRangeException(nameof(state), state, null)
            };
        }
    }
}
