// <auto-generated>
// This file is auto-generated. Do not edit manually.
// </auto-generated>

using System;
using Utils.Enum;

namespace GameStates
{
    public static class GameStateFactory
    {
        public static IGameState Create(NamedState state)
        {
            return state switch
            {
                NamedState.MainMenu => new MainMenuState(),
                _ => throw new ArgumentOutOfRangeException(nameof(state), state, null)
            };
        }
    }
}
