// <auto-generated>
// Do not edit manually.
// </auto-generated>

using System;
using Model.Enum.Named;
using Player.PlayerActions;

namespace Player.PlayerActions
{
    public static class PlayerActionFactory
    {
        public static IPlayerAction Create(NamedPlayerAction action)
        {
            return action switch
            {
                NamedPlayerAction.QuickSaveAndLoad => new QuickSaveAndLoadAction(),
                _ => throw new ArgumentOutOfRangeException(nameof(action), action, null)
            };
        }
    }
}
