// <auto-generated>
// This file is auto-generated. Do not edit manually.
// </auto-generated>

namespace Model.Enum.Named
{
    public enum NamedState
    {
        GameLoad,
        Gameplay,
        MainMenu,
        PauseMenu
    }
}
