using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using GameStates;
using UnityEditor;
using UnityEngine.UIElements;
using Utils.Enum;

namespace Editor.CommandCenter.Modules
{
    public class GameStateSyncModule : IEditorModule
    {
        public string ModuleName => "Game State Synchronizer";

        public ModuleStatus Status { get; private set; } = ModuleStatus.Unknown;

        public float MinHeight => 0;
        public float MaxHeight => 0;

        private ICommandCenterLogger _logger;

        private const string EnumPath =
            "Assets/Scripts/Utils/Enum/NamedState.cs";

        private const string FactoryPath =
            "Assets/Scripts/GameStates/GameStateFactory.cs";

        public void Initialize(ICommandCenterLogger logger)
        {
            _logger = logger;
        }

        public VisualElement CreateContent()
        {
            var root = new VisualElement();
            root.Add(new Label("Ensures NamedState enum and GameStateFactory match IGameState implementations."));
            return root;
        }

        public void Validate()
        {
            var stateTypes = GetGameStateTypes();
            var enumNames = Enum.GetNames(typeof(NamedState));

            var missingEnums = stateTypes
                .Select(t => t.Name.Replace("State", ""))
                .Where(name => !enumNames.Contains(name))
                .ToList();

            var extraEnums = enumNames
                .Where(e => !stateTypes.Any(t => t.Name.StartsWith(e)))
                .ToList();

            if (!missingEnums.Any() && !extraEnums.Any())
            {
                Status = ModuleStatus.Valid;
                _logger.Log("GameState system is synchronized.");
            }
            else
            {
                Status = ModuleStatus.Warning;

                if (missingEnums.Any())
                    _logger.LogWarning("Missing enum entries: " + string.Join(", ", missingEnums));

                if (extraEnums.Any())
                    _logger.LogWarning("Enum values without state class: " + string.Join(", ", extraEnums));
            }
        }

        public void Enforce()
        {
            var stateTypes = GetGameStateTypes();
            var stateNames = stateTypes
                .Select(t => t.Name.Replace("State", ""))
                .OrderBy(n => n)
                .ToArray();

            GenerateEnum(stateNames);
            GenerateFactory(stateNames);

            Status = ModuleStatus.Valid;
            _logger.Log("GameState enum and factory synchronized.");
        }

        private static Type[] GetGameStateTypes()
        {
            return Assembly.GetAssembly(typeof(IGameState))
                .GetTypes()
                .Where(t =>
                    typeof(IGameState).IsAssignableFrom(t) &&
                    !t.IsInterface &&
                    !t.IsAbstract)
                .ToArray();
        }

        private void GenerateEnum(string[] stateNames)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// This file is auto-generated. Do not edit manually.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
            builder.AppendLine("namespace Utils.Enum");
            builder.AppendLine("{");
            builder.AppendLine("    public enum NamedState");
            builder.AppendLine("    {");

            for (var i = 0; i < stateNames.Length; i++)
            {
                builder.Append("        " + stateNames[i]);
                if (i < stateNames.Length - 1)
                    builder.Append(",");
                builder.AppendLine();
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");

            WriteIfChanged(EnumPath, builder.ToString());
        }

        private void GenerateFactory(string[] stateNames)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// This file is auto-generated. Do not edit manually.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
            builder.AppendLine("using System;");
            builder.AppendLine("using Utils.Enum;");
            builder.AppendLine();
            builder.AppendLine("namespace GameStates");
            builder.AppendLine("{");
            builder.AppendLine("    public static class GameStateFactory");
            builder.AppendLine("    {");
            builder.AppendLine("        public static IGameState Create(NamedState state)");
            builder.AppendLine("        {");
            builder.AppendLine("            return state switch");
            builder.AppendLine("            {");

            foreach (var name in stateNames)
            {
                builder.AppendLine($"                NamedState.{name} => new {name}State(),");
            }

            builder.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(state), state, null)");
            builder.AppendLine("            };");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            WriteIfChanged(FactoryPath, builder.ToString());
        }

        private void WriteIfChanged(string path, string newContent)
        {
            if (File.Exists(path))
            {
                var current = File.ReadAllText(path);
                if (current == newContent)
                {
                    _logger.Log("No changes required: " + Path.GetFileName(path));
                    return;
                }
            }

            File.WriteAllText(path, newContent);
            AssetDatabase.Refresh();

            _logger.Log("Updated: " + Path.GetFileName(path));
        }
    }
}