using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

namespace Editor.CommandCenter.Utils
{
    public static class EnumSynchronizer
    {
        public static void Synchronize(
            string enumPath,
            string enumNamespace,
            string enumName,
            string[] values,
            ICommandCenterLogger logger = null)
        {
            values = values
                .Where(v => !string.IsNullOrWhiteSpace(v))
                .Distinct()
                .OrderBy(v => v)
                .ToArray();

            var content = Generate(enumNamespace, enumName, values);

            if (File.Exists(enumPath))
            {
                var current = File.ReadAllText(enumPath);
                if (current == content)
                {
                    logger?.Log($"No changes required: {Path.GetFileName(enumPath)}");
                    return;
                }
            }

            File.WriteAllText(enumPath, content);
            AssetDatabase.Refresh();

            logger?.Log($"Updated enum: {Path.GetFileName(enumPath)}");
        }

        private static string Generate(
            string enumNamespace,
            string enumName,
            string[] values)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// This file is auto-generated. Do not edit manually.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
            builder.AppendLine($"namespace {enumNamespace}");
            builder.AppendLine("{");
            builder.AppendLine($"    public enum {enumName}");
            builder.AppendLine("    {");

            for (var i = 0; i < values.Length; i++)
            {
                builder.Append("        " + values[i]);
                if (i < values.Length - 1)
                    builder.Append(",");
                builder.AppendLine();
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }
    }
}