using System;
using System.IO;
using System.Linq;
using System.Text;
using Editor.CommandCenter.Utils;
using Model.Enum.Named;
using UnityEditor;
using UnityEngine.UIElements;
using Player.PlayerActions;

namespace Editor.CommandCenter.Screens.Modules.Validation
{
    public class PlayerActionSyncValidationModule : IEditorValidationModule
    {
        public string ModuleName => "Player Action Synchronizer";

        public ModuleStatus Status { get; private set; } = ModuleStatus.Unknown;

        private ICommandCenterLogger _logger;

        private const string EnumPath =
            "Assets/Scripts/Model/Enum/Named/NamedPlayerAction.cs";

        private const string FactoryPath =
            "Assets/Scripts/Player/PlayerActions/PlayerActionFactory.cs";

        public void Initialize(ICommandCenterLogger logger)
        {
            _logger = logger;
        }

        public VisualElement CreateContent()
        {
            var root = new VisualElement();
            root.Add(new Label(
                "Synchronizes NamedPlayerAction enum, IPlayerAction implementations, and PlayerActionFactory."));
            return root;
        }

        public void Validate()
        {
            var actionTypes = GetActionTypes();
            var enumNames = Enum.GetNames(typeof(NamedPlayerAction));

            var missingEnums = actionTypes
                .Select(t => StripSuffix(t.Name, "Action"))
                .Where(name => !enumNames.Contains(name))
                .ToList();

            var extraEnums = enumNames
                .Where(e => !actionTypes.Any(t => t.Name.StartsWith(e)))
                .ToList();

            if (!missingEnums.Any() && !extraEnums.Any())
            {
                Status = ModuleStatus.Valid;
                _logger.Log("PlayerAction system is synchronized.");
                return;
            }

            Status = ModuleStatus.Warning;

            if (missingEnums.Any())
                _logger.LogWarning("Missing enum entries: " + string.Join(", ", missingEnums));

            if (extraEnums.Any())
                _logger.LogWarning("Enum values without implementation: " + string.Join(", ", extraEnums));
        }

        public void Enforce()
        {
            var actionTypes = GetActionTypes();

            var actionNames = actionTypes
                .Select(t => StripSuffix(t.Name, "Action"))
                .OrderBy(n => n)
                .ToArray();

            EnumSynchronizer.Synchronize(
                EnumPath,
                "Model.Enum.Named",
                "NamedPlayerAction",
                actionNames,
                _logger);

            GenerateFactory(actionNames);

            Status = ModuleStatus.Valid;
            _logger.Log("PlayerAction enum and factory synchronized.");
        }

        private static Type[] GetActionTypes()
        {
            return AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(a =>
                {
                    try { return a.GetTypes(); }
                    catch { return Array.Empty<Type>(); }
                })
                .Where(t =>
                    typeof(IPlayerAction).IsAssignableFrom(t) &&
                    t.IsClass &&
                    !t.IsAbstract)
                .ToArray();
        }

        private void GenerateFactory(string[] actionNames)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using Model.Enum.Named;");
            sb.AppendLine("using Player.PlayerActions;");
            sb.AppendLine();
            sb.AppendLine("namespace Player.PlayerActions");
            sb.AppendLine("{");
            sb.AppendLine("    public static class PlayerActionFactory");
            sb.AppendLine("    {");
            sb.AppendLine("        public static IPlayerAction Create(NamedPlayerAction action)");
            sb.AppendLine("        {");
            sb.AppendLine("            return action switch");
            sb.AppendLine("            {");

            foreach (var name in actionNames)
            {
                sb.AppendLine($"                NamedPlayerAction.{name} => new {name}Action(),");
            }

            sb.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(action), action, null)");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            WriteIfChanged(FactoryPath, sb.ToString());
        }

        private void WriteIfChanged(string path, string newContent)
        {
            if (File.Exists(path))
            {
                var current = File.ReadAllText(path);
                if (current == newContent)
                {
                    _logger.Log("No changes required: " + Path.GetFileName(path));
                    return;
                }
            }

            File.WriteAllText(path, newContent);
            AssetDatabase.Refresh();

            _logger.Log("Updated: " + Path.GetFileName(path));
        }

        private static string StripSuffix(string input, string suffix)
        {
            return input.EndsWith(suffix)
                ? input.Substring(0, input.Length - suffix.Length)
                : input;
        }
    }
}